#!/usr/bin/env python3
"""Regenerate docs/source.js from main.swift.

The landing page's whole argument is a line count, so nothing on it is typed by
hand: region counts, the manifest ranges and the readable source all come from here.
Run this after any change to main.swift, or the page starts lying.
"""
import hashlib, io, json, os, re, html

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, os.pardir, "main.swift")

REGIONS = [
    ("Imports and settings",        1, 14),
    ("Overlay state and init",     15, 44),
    ("Drawing the overlay",        45, 131),
    ("Mouse: select and annotate",132, 179),
    ("Keyboard",                  180, 203),
    ("Toolbar",                   204, 262),
    ("Export: copy and save",     263, 287),
    ("OCR",                       288, 382),
    ("Window and capture",        383, 431),
    ("Global hotkey",             432, 439),
    ("App and launch",            440, 459),
]

# numbers the page quotes in prose; generated so they cannot be hand-typed wrong
FUNCS = {"layout": (330, 379, "func layout")}

# the OCR demo reconstructs the very loop that does the reconstruction
SAMPLE = (366, 377)

KW = {"var","let","for","in","if","else","guard","return","func","static","struct",
      "continue","nil","true","false","enum","class","final","import","case","switch",
      "override","private","weak","self","defer","throws","try","init","extension"}

def code_lines(lines):
    return sum(1 for l in lines if l.strip() and not l.strip().startswith("//"))

def highlight(line):
    i = line.find("//")
    code, comment = (line[:i], line[i:]) if i >= 0 else (line, "")
    out = ""
    for tok in re.split(r'(\W)', code):
        esc = html.escape(tok)
        if tok in KW:                              out += '<span class="k">%s</span>' % esc
        elif re.fullmatch(r'\d+(\.\d+)?', tok):    out += '<span class="num">%s</span>' % esc
        else:                                       out += esc
    if comment:                                     out += '<span class="c">%s</span>' % html.escape(comment)
    return out

def block(lines, dedent=True):
    n = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0) if dedent else 0
    return "\n".join(highlight(l[n:]) if l.strip() else "" for l in lines)

def main():
    src = io.open(SRC, encoding="utf-8").read().split("\n")
    if src and src[-1] == "": src.pop()

    regions, total = [], 0
    for name, a, b in REGIONS:
        chunk = src[a-1:b]
        n = code_lines(chunk)
        total += n
        regions.append({"name": name, "from": a, "to": b, "lines": n,
                        "html": block(chunk)})

    counted = code_lines(src)
    assert total == counted, "regions cover %d lines, file has %d" % (total, counted)

    funcs = {}
    for name, (a, b, needle) in FUNCS.items():
        head, tail = src[a-1], src[b-1]
        assert needle in head, "%s: line %d is not '%s'" % (name, a, needle)
        assert tail.strip() == "}", "%s: line %d is not the closing brace" % (name, b)
        funcs[name] = code_lines(src[a-1:b])

    smp = src[SAMPLE[0]-1:SAMPLE[1]]
    assert all(l.strip() for l in smp), "sample range contains a blank line"
    sded = min(len(l) - len(l.lstrip()) for l in smp)
    sample = [l[sded:] for l in smp]
    assert max(len(l) for l in sample) <= 92, "sample too wide for the stage"

    data = {"total": total, "fileLines": len(src), "funcs": funcs,
            "sample": sample, "sampleFrom": SAMPLE[0], "sampleTo": SAMPLE[1],
            "regions": regions}

    _rewrite_noscript(regions, total, len(src))

    payload = json.dumps(data, ensure_ascii=False)
    digest = hashlib.sha1(payload.encode("utf-8")).hexdigest()[:8]

    out = os.path.join(HERE, "source.js")
    io.open(out, "w", encoding="utf-8").write(
        "/* generated by sync.py from main.swift - do not edit */\n"
        "window.SHOTTY=" + payload + ";\n")
    _stamp_script(digest)
    print("source.js: %d regions, %d code lines, %d total lines, funcs %s, sample %d-%d (%d cols)"
          % (len(regions), total, len(src), funcs, SAMPLE[0], SAMPLE[1],
             max(len(l) for l in sample)))

def _stamp_script(digest):
    """Version the script tag. Every number on the page comes out of this file, so a
    cached copy is not a stale asset, it is the page quoting figures that moved."""
    page = os.path.join(HERE, "index.html")
    if not os.path.exists(page):
        return
    s = io.open(page, encoding="utf-8").read()
    new = re.sub(r'src="source\.js(?:\?v=[0-9a-f]+)?"', 'src="source.js?v=%s"' % digest, s)
    if new != s:
        io.open(page, "w", encoding="utf-8").write(new)
        print("index.html: source.js stamped v=%s" % digest)


def _rewrite_noscript(regions, total, file_lines):
    """Keep the no-JavaScript copy of the table identical to the generated one."""
    page = os.path.join(HERE, "index.html")
    if not os.path.exists(page):
        return
    s = io.open(page, encoding="utf-8").read()
    start, end = "<!--manifest-noscript-->", "<!--/manifest-noscript-->"
    if start not in s or end not in s:
        print("index.html: manifest-noscript marker missing, left alone")
        return
    rows = "\n".join('        <tr><td>%s</td><td>%s&#8211;%s</td><td>%s</td></tr>'
                     % (r["name"], r["from"], r["to"], r["lines"]) for r in regions)
    a = s.index(start)
    b = s.index(end) + len(end)
    old = s[a:b]
    head = old[:old.index("<table")]                 # keep the prose, replace only the table
    tail = old[old.index("</table>"):]
    block = (head + '<table class="keys ns">\n'
             '        <tr><th>Region</th><th>Lines</th><th>Code</th></tr>\n' + rows +
             '\n        <tr><td><b>main.swift</b></td><td>1&#8211;%d</td><td><b>%d</b></td></tr>\n'
             '      ' % (file_lines, total) + tail)
    s = s[:a] + block + s[b:]
    io.open(page, "w", encoding="utf-8").write(s)
    print("index.html: noscript table refreshed")


if __name__ == "__main__":
    main()
